[package]
name = "git-open-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.15"
url = "2.3.1"
ssh2-config = "0.1.3"
webbrowser = "0.8.2"
